-- Сначала удаляем таблицы, которые ССЫЛАЮТСЯ на другие
drop table if exists tags cascade;
drop table if exists item_notes cascade;
drop table if exists items cascade;
drop table if exists users cascade;

-- Теперь создаём в правильном порядке
create table users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) UNIQUE,
                       first_name VARCHAR(255),
                       last_name VARCHAR(255),
                       registration_date TIMESTAMP,
                       user_state VARCHAR(50) CHECK (user_state IN ('ACTIVE', 'BLOCKED', 'DELETED'))
);

create table items (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_id BIGINT,
                       url VARCHAR(500)
);

create table tags (
                      name VARCHAR(100),
                      item_id BIGINT references items(id)
);

create table item_notes (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            text VARCHAR(2000),
                            item_id BIGINT references items(id),
                            date VARCHAR(50)
);
